version: '3.8'

services:
   
  remix-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: frontend_remix_stevie
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    networks:
      - my_custom_network
    volumes:
      # If you need to persist any data
      - ./data:/app/data
      # For static assets that might change
      - ./public:/app/public 
     

networks:
  my_custom_network:
    driver: bridge