# Generated by Django 5.2 on 2025-04-07 10:02

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('sku', models.CharField(default=product.models.generate_uuid, max_length=100, unique=True)),
                ('csv_file', models.FileField(upload_to='product_csv_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
