# Generated by Django 5.2 on 2025-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='product_excel_files/'),
        ),
    ]
