# Generated by Django 5.2 on 2025-04-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
