# Generated by Django 5.2 on 2025-04-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
