# Generated by Django 5.2 on 2025-04-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='label',
        ),
    ]
